"""Irodori TTS emoji allowlist — mirrors irodori_tts.gradio_emoji_palette (VoiceDesign)."""

from __future__ import annotations

# Source: Irodori-TTS gradio_emoji_palette.py EMOJI_PALETTE_ITEMS
IRODORI_EMOJI_ALLOWLIST: frozenset[str] = frozenset(
    {
        "👂",
        "😮‍💨",
        "⏸️",
        "🤭",
        "🥵",
        "📢",
        "😏",
        "🥺",
        "🌬️",
        "😮",
        "👅",
        "💋",
        "🫶",
        "😭",
        "😱",
        "😪",
        "😴",
        "⏩",
        "📞",
        "🐢",
        "🥤",
        "🤧",
        "😒",
        "😰",
        "😆",
        "💥",
        "😠",
        "😲",
        "🥱",
        "😖",
        "😟",
        "🫣",
        "🙄",
        "😊",
        "😎",
        "👌",
        "🙏",
        "🥴",
        "🎵",
        "🤐",
        "😌",
        "🤔",
        "💪",
        "👃",
        "📖",
    }
)

IRODORI_EMOJI_REFERENCE: tuple[tuple[str, str], ...] = (
    ("😊", "嬉しげ"),
    ("🤔", "疑問"),
    ("🤭", "くすっ"),
    ("😮‍💨", "溜息"),
    ("😭", "悲しげ"),
    ("⏩", "早口"),
    ("🐢", "ゆっくり"),
    ("⏸️", "間"),
    ("😆", "喜び"),
    ("😠", "怒り"),
    ("😲", "驚き"),
    ("😌", "安堵"),
    ("🥺", "震え声"),
    ("😏", "からかい"),
    ("👂", "囁き"),
    ("🤧", "咳"),
)
